# Generated by Django 2.1 on 2019-01-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_by',
            field=models.CharField(default=1, max_length=360),
            preserve_default=False,
        ),
    ]
