# Generated by Django 2.1.4 on 2019-01-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liked_by',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
    ]
