# Generated by Django 2.1.4 on 2019-01-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_auto_20190107_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='comment_by',
        ),
    ]
