# Generated by Django 2.1.4 on 2019-01-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20190107_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='person',
        ),
    ]
